### ISSUE TITLE
RuntimeError: header invalid

### ISSUE THREAD

**Issue by veggiedefender** [skadistats/smoke#18]
When I try to parse a replay (I've only tried game 2379320481 so far, Na'vi vs OG) I get `RuntimeError: header invalid`.

I'm running it with python 2.7.11 on arch (64 bit).

Here's what I have installed:
- Cython 0.21
- [Snappy](https://www.archlinux.org/packages/extra/x86_64/snappy/) and [Protobuf](https://www.archlinux.org/packages/extra/i686/protobuf/) from the official repositories
- python-snappy, whichever one is the latest on pip
- palm 0.1.9, I followed `readme.md`'s instructions

I tried downloading the replay twice, and I got the error both times, so I don't think it got corrupted or anything.

Here's a google drive link to my demo file

https://drive.google.com/file/d/0B7IfL3SQIKieN29yTG1fVXBzQmc/view?usp=sharing

**Comment by spheenik** [comment]
Smoke can only read replays in the Source 1 format. Afaik, there is no python-parser capable of reading Source 2. You can use [clarity](https://github.com/skadistats/clarity) or [manta](https://github.com/dotabuff/manta) to parse S2 replays.

**Comment by KaiWangCanada** [comment]
What is Source 1 format? How to get the Source 1 format? Thanks!

**Comment by spheenik** [comment]
Early Dota 2 replays (before Dota 2 Reborn, which came out mid 2015).
Replays before that are Source 1.
So if you want some, you can download TI 3 replays ^^
