### ISSUE TITLE
No smoke /io /peek.c file

### ISSUE THREAD

**Issue by roamin-ronin** [skadistats/smoke#4]
Trying to install on mavericks. I'm on the final install of smoke, using the readme, when I get this:

```
building 'smoke.io.peek' extension
cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -Wunused-command-line-argument-hard-error-in-future -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c smoke/io/peek.c -o build/temp.macosx-10.9-intel-2.7/smoke/io/peek.o
clang: error: no such file or directory: 'smoke/io/peek.c'
clang: error: no input files
error: command 'cc' failed with exit status 1
```

gcc version 4.2.1
Xcode CL tools 5.1
Clang:
Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix

**Comment by onethirtyfive** [comment]
Hi @roamin-ronin,

I'm sad to say this, but I have no idea what's going on here. Maybe someone can swing by and help. Did you ask in #dota2replay?

Sorry, wish I could help.

**Comment by jptaylor** [comment]
You can bypass this by running:

```
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments
```

Mavericks is bit weird when it comes to the Python C libraries, so ignoring the errors normally works out fine.

**Comment by onethirtyfive** [comment]
Thanks, @jptaylor. I'll add that to the README.
