### ISSUE TITLE
UserMessages Missing

### ISSUE THREAD

**Issue by Decoud** [skadistats/smoke#5]
I've gotten a 'KeyError: 124' for some matches in 6.80: 517967240, 612904121, 603516314, 513035794 . Looking at https://raw.githubusercontent.com/skadistats/smoke/master/smoke/protobuf/dota2_palm.py , it appears that the 'DOTA_UM_' end at 122. Clarity ( https://raw.githubusercontent.com/skadistats/clarity/master/src/main/java/com/dota2/proto/DotaUsermessages.java ) appears to have 123 and 124.

I'm still looking at 6.81 examples but found another one. I got the 'KeyError: 127' for match 656762659 . So it appears that the UserMessages go up to at least 127 (Clarity stops at 124, I don't think it has been updated for 6.81 yet).

**Comment by onethirtyfive** [comment]
Fixed in master.
