### ISSUE TITLE
Creep attacks by players

### ISSUE THREAD

**Issue by psinger** [skadistats/smoke#6]
Hi!

First of all, really great library. 

I am currently trying to parse the following information out of replay data: Get the location of a player that attacks any unit (creep or other hero) at a specific point of time. So e.g., I want to get the location of all players that attack units between minutes 1 and 2.

I am unsure of how to exactly retrieve this data though. I guess it is possible. Is there a documentation about all the fields returned somewhere? Maybe someone also has a concrete idea of how I could approach this.

Cheers!

**Comment by spheenik** [comment]
Hey!

you have to make a distinction between spell damage and physical damage (right click).
Spell damage can be deducted (via combat log and/or modifiers).
The only way to see physical damage (I know of), is that the health of the corresponding entity (the one taking the hit) goes down. What sucks however, is that the damage-source is not encoded in the replay. So you could try to correlate stuff (animation phases, sounds, proximity of heroes) to find out who did the damage. I don't know if it ever has been tried though… so… try to channel the pioneer in yourself ;-)
